Repository canonical/design.ubuntu.com, pull requests merged in 2023-01, with the labels that each got.

#225 GitHub actions
  .circleci/config.yml
  .github/workflows/pr.yaml
  package.json
Labels: Review: Code +1, Maintenance 🔨

#258 WD-1297 build new resources page
  _data/logos.yaml
  redirects.yaml
  requirements.txt
  sass/_pattern_font-tester.scss
  sass/main.scss
  templates/_layouts/_root.html
  templates/_layouts/page.html
  templates/downloads/index.html
  templates/resources/index.html
  webapp/app.py
Labels: Review: QA needed, Review: Design needed, Review: Code needed

#268 update flask-base and ubuntu base image
  Dockerfile
  requirements.txt
Labels: Review: Code +1, Maintenance 🔨

#266 WD-1297 add dark mode switch to and redesign icon set and logos sections
  _data/icons.yaml
  _data/logos.yaml
  _data/resources.yaml
  sass/main.scss
  templates/resources/index.html
  webapp/app.py
Labels: Review: QA needed, Review: Design needed, Review: Code needed

#273 Apply new full width layout to design site home page
  package.json
  templates/_layouts/_root.html
  templates/index.html
  yarn.lock
Labels: Review: QA needed, Review: Code needed

#271 WD-1359 revisit the font page
  sass/_pattern_font-tester.scss
  static/js/font.js
  templates/_layouts/_root.html
  templates/font/index.html
Labels: Review: Code +1, Review: QA +1

#274 WD-1299 use new vanilla layout on design ubuntu com site
  templates/404.html
  templates/accessibility/index.html
  templates/contribute/index.html
  templates/font/index.html
  templates/index.html
  templates/resources/index.html
Labels: Review: Code +1, Review: QA +1

#262 Build the first draft of the new brand page WD-1343
  Dockerfile
  requirements.txt
  sass/main.scss
  templates/_layouts/page.html
  templates/brand/index.html
  templates/vanilla/index.html
Labels: Review: Design needed, Review: Code +1
